version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0.0
  sign-packages: opennms/sign-packages@<< pipeline.parameters.dev-orb-version >>

parameters:
  dev-orb-version:
    type: string
    default: "dev:alpha"

workflows:
  verify-and-publish:
    jobs:
      - orb-tools/lint:
          filters:
            tags:
              only: /.*/
      - orb-tools/pack:
          artifact-path: sign-packages.yml
          destination-orb-path: sign-packages.yml
          workspace-path: sign-packages.yml
          source-dir: sign-packages
          filters:
            tags:
              only: /.*/
      - orb-tools/publish:
          attach-workspace: true
          orb-path: workspace/sign-packages.yml
          orb-ref: opennms/sign-packages@<< pipeline.parameters.dev-orb-version >>
          filters:
            tags:
              only: /.*/
          requires:
            - orb-tools/lint
            - orb-tools/pack
